site_name: Q

site_author: sweetser@alum.mit.edu

theme_dir: spacelab-mod

dev_addr: 127.0.0.1:8004

google_analytics: ['UA-9710248-1', 'quaternions.com']

markdown_extensions: [include, subscript, superscript, footnotes]

pages:
- [index.md, '']
- [Math/math.md, Math, The Math]
- [Math/overview.md, Math, Overview]
- [Math/history.md, Math, History]
- [Math/numbers_101.md, Math, Numbers 101]
- [Math/multiplying.md, Math, Easy multiplying]
- [Math/products.md, Math, Products]
- [Math/scalars_vectors.md, Math, 'Scalars, vectors, tensors and all that']
- [Math/analysis.md, Math, Analysis]
- [Math/topology.md, Math, Topology]
- [Math/fit.md, Math, Where quaternions fit]
- [Math/tools.md, Math, Tools]
  # - [Math/dynamic_graphs.md, Math, Dynamic graphs]
- [Classical_physics/classical_physics.md, Classical, Classical physics]
- [Classical_physics/force.md, Classical, Forces]
- [Classical_physics/sho.md, Classical, Simple Harmonic Oscillators]
- [Classical_physics/conservative_force.md, Classical, Conservative force]
- [SR/special_relativity.md, SR, Special Relativity (SR)]
- [SR/problem_sets.md, SR, Problem sets]
- [SR/problem_set_1.md, SR, Problem set 1]
- [Gravity/gravity.md, Gravity, Quaternion gravity]
- [Gravity/Measurement-101/measure.md, Gravity, Measurement-101 - Measuring Events]
- [Gravity/Measurement-101/special_relativity.md, Gravity, Measurement-101 - Special relaitivity]
- [Gravity/Measurement-101/quaternion_gravity.md, Gravity, Measurement-101 - Quaternion Gravity]
- [Gravity/Measurement-101/measure_it_all.md, Gravity, Measurement-101 - SR + QG: Special Relativity and Quaternion Gravity]
- [Gravity/space-times-time_invariance.md, Gravity, Quaternion space-times-time invariance as gravity]
- [Gravity/essays_on_gravitation.md, Gravity, Essays on gravitation contest]
- [EM/em.md, EM, Electromagnetism]
- [EM/derive_Euler-Lagrange.md, EM, Derive the Euler-Lagrange equations]
- [EM/EM_invariants.md, EM, EM invariants]
- [EM/derive_Maxwell_homogeneous_equations.md, EM, Derive the Maxwell homogeneous equations]
- [EM/derive_Maxwell_source_equations.md, EM, Derive the Maxwell source equations]
- [QM/qm.md, QM, Quantum Mechanics]
- [QM/bracket_notation.md, QM, Bracket notation and quaternions]
- [QM/polar.md, QM, Multiplying polar representations]
- [QM/uncertainty_principle.md, QM, Commutators and the uncertainty principle]
- [QM/spin_and_angular_momentum.md, QM, Spin and angular momentum]
- [QM/Schrodinger.md, QM, The Schrodinger equation]
- [QM/Klein-Gordon.md, QM, The Klein-Gordon equation]
- [QM/standard_model_symmetries.md, QM, Visualizing the standard model]
- [QM/time_reversal.md, QM, Time reversal]
- [Stuff/buttons.md, Stuff, Buttons]
- [About/professional_sketch.md, About, Professional sketch]
- [About/personal_sketch.md, About, Personal Sketch]
- [About/lindy_hop.md, About, Lindy Hop]
- [About/bike.md, About, The bike]
- [About/thanks.md, About, Thanks]
- [About/todo.md, About, To do]
- [About/todo.md, About, To do]
- [About/todo.md, About, To do]
- [About/contact_and_tip.md, About, Contact and tips]
