site_name: Q

site_author: sweetser@alum.mit.edu

theme: spacelab

dev_addr: 127.0.0.1:8004

google_analytics: ['UA-9710248-1', 'dougsweetser.github.io/Q']

markdown_extensions: 
    - footnotes
    - pymdownx.arithmatex:
        generic: true

plugins:
    - exclude:
        glob:
            - "*book.md*"
            - "doing_physics.md"

nav:
- '': index.md
- Math:
    - 'The Math': 'Math/math.md'
    - 'Overview': 'Math/overview.md'
    - 'History': 'Math/history.md'
    - 'Numbers 101': 'Math/numbers_101.md'
    - 'Easy multiplying': 'Math/multiplying.md'
    - 'Products': 'Math/products.md'
    - 'Scalars, vectors, tensors and all that': 'Math/scalars_vectors.md'
    - 'Complex quaternions': 'Math/complex_quaternions.md'
    - 'Quaternion equivalence classes': 'Math/equivalence_classes.md'
    - 'Analysis': 'Math/analysis.md'
    - 'Topology': 'Math/topology.md'
    - 'Where quaternions fit': 'Math/fit.md'
    - 'Math, Tools': 'Math/tools.md'
  # - 'Math/dynamic_graphs.md, Math, Dynamic graphs'
- Classical:
    - 'Classical physics': 'Classical_physics/classical_physics.md'
    - 'Forces': 'Classical_physics/force.md'
    - 'Simple Harmonic Oscillators': 'Classical_physics/sho.md'
    - 'Conservative force': 'Classical_physics/conservative_force.md'
- SR:
    - 'Special Relativity (SR)': 'SR/special_relativity.md'
    - 'Problem sets': 'SR/problem_sets.md' 
    - 'Problem set 1': 'SR/problem_set_1.md'
    - 'Totally ordered_sets in Space-time': 'SR/totally_ordered_sets_in_space-time.md'
- Gravity:
    - 'Quaternion gravity in 2 pages': 'Stuff/pdfs/quaternion_gravity_in_2_pages.pdf'
    - 'Three roads to quaternion gravity': 'Gravity/three_roads_to_quaternion_gravity.md'
    - 'Measurement 101 - Measuring Events': 'Gravity/Measurement_101/measure.md' 
    - 'Gravity, Measurement_101 - Special relaitivity': 'Gravity/Measurement_101/special_relativity.md' 
    - 'Measurement 101 - Quaternion Gravity': 'Gravity/Measurement_101/quaternion_gravity.md'
    - 'Measurement 101 - SR + QG: Special Relativity and Quaternion Gravity': 'Gravity/Measurement_101/measure_it_all.md'
    - 'Quaternion space-times-time invariance as gravity': 'Gravity/space-times-time_invariance.md'
    - 'Essays on gravitation contest': 'Gravity/essays_on_gravitation.md'
    - 'PGT - Personal Gravity Theory': 'Gravity/PGT/personal_gravity_theory.md'
- EM:
    - 'Electromagnetism': 'EM/em.md'
    - 'Derive the Euler-Lagrange equations': 'EM/derive_Euler-Lagrange.md'
    - 'EM invariants': 'EM/EM_invariants.md'
    - 'Derive the Maxwell homogeneous equations': 'EM/derive_Maxwell_homogeneous_equations.md'
    - 'Derive the Maxwell source equations': 'EM/derive_Maxwell_source_equations.md'
    - 'Derive the Maxwell source equations by hand': 'EM/Maxwell_by_hand.md'
    - 'Jupyter notebook derivation': 'EM/2022-02-06__Maxwell_derivation.pdf'
- QM:
    - 'Quantum Mechanics': 'QM/qm.md'
    - "Bell's Future QM Interpretation": "QM/BellsFuture.md"
    - 'Bracket notation and quaternions': 'QM/bracket_notation.md'
    - 'Multiplying polar representations': 'QM/polar.md'
    - 'Commutators and the uncertainty principle': 'QM/uncertainty_principle.md'
    - 'Spin and angular momentum': 'QM/spin_and_angular_momentum.md'
    - 'The Schrodinger equation': 'QM/Schrodinger.md'
    - 'The Klein-Gordon equation': 'QM/Klein-Gordon.md'
    - 'Visualizing the standard model': 'QM/standard_model_symmetries.md'
    - 'Time reversal': 'QM/time_reversal.md'
- Art + PDFs:
    - 'Art Portfolio': 'Stuff/art.md'
    - 'Buttons': 'Stuff/buttons.md'
    - 'PDFs': 'Stuff/pdfs/pdfs.md'
    - 'Talks on Gravity': 'Stuff/Talks/talks.md'
    - 'Buy Stuff': 'Stuff/shop.md'
- Blogs:
    - 'Some writings': 'Blogs/blogs.md'
    - 'Bet against Lubos': 'Blogs/Bet_against_Lubos/bet_against_Lubos.md'
    - 'Discovery': 'Blogs/Discovery/discovery.md'
    - 'Electromagnetism and gravity': 'Blogs/Electromagnetism_and_gravity/electromagnetism_and_gravity.md'
    - 'Outreach efforts': 'Blogs/Outreach_efforts/outreach_efforts.md'
    - 'Paper': 'Blogs/Paper/paper.md'
    - 'Space-time numbers': 'Blogs/Space-time_numbers/space-time_numbers.md'
    - 'The Plan': 'Blogs/The_plan/the_plan.md'
    - 'Working with space-time numbers': 'Blogs/Working_with_space-time_numbers/working_with_space-time_numbers.md'
    - 'Zero and one': 'Blogs/Zero_and_one/zero_and_one.md'
- About:
    - 'Professional sketch': 'About/professional_sketch.md'
    - 'Resume': 'About/resume.md'
    - 'Personal Sketch': 'About/personal_sketch.md'
    - 'Lindy Hop': 'About/lindy_hop.md'
    - 'The bike': 'About/bike.md'
    - 'Thanks': 'About/thanks.md'
    - 'To do': 'About/todo.md'
    - 'Contact and tips': 'About/contact_and_tip.md'
